<?php 

use Drupal\Core\Database\Database;


function as_league_db_connection(){

  return Database::getConnection();
}

/**
 * Implements hook_theme().
 */
function as_league_theme() {

    return [
      'organization_table' => [
        'variables' => [
          'header' => [],
          'rows' => [],
          'pager' => NULL,
          'add_url' => '',
        ],
        'template' => 'organization-table',
      ],
      'season-listing' => [
        'variables' => [
          'header' => [],
          'rows' => [],
          'pager' => NULL,
          'add_url' => '',
        ],
        'template' => 'season-listing',
      ],
    ];
  }


function as_league_season_load($season_name){

  $as_league_season = as_league_db_connection()->select('as_league_season', 'season')->fields('season')->condition('season_name', $season_name)->execute()->fetchObject();

  if($as_league_season){
    return $as_league_season;
  }else{
    return FALSE;
  }
}//EO as_league_season_load


function as_league_season_save($as_league_season){

  $result = as_league_db_connection()->upsert('as_league_season')->fields($as_league_season)->key('season_name')->execute();

	if($result){
		return TRUE;
	}else{
    return FALSE;
	}
}//EO as_league_season_save


function as_league_org_load($org_id){

  $as_league_org = as_league_db_connection()->select('as_league_orgs', 'org')->fields('org')->condition('org_id', $org_id)->execute()->fetchObject();

  if($as_league_org){
    return $as_league_org;
  }else{
    return FALSE;
  }
}//EO as_league_season_load

function as_league_org_save($as_league_org){

  $result = as_league_db_connection()->upsert('as_league_orgs')->fields($as_leagas_league_orgue_season)->key('org_id')->execute();

	if($result){
		return TRUE;
	}else{
    return FALSE;
	}
}//EO as_league_org_save